---
- name: Template for user creation SQL
  template:
    src: user_creation.sql.j2
    dest: /tmp/user_creation.sql

- name: Create HANACOCKPIT User in tenantDB
  shell: hdbsql -i {{ hana_instance }} -u SYSTEM -p {{ hana_tenantDB_password }} -d {{ hana_sid }} -I /tmp/user_creation.sql
  register: tenant_db_output
  environment:
    LD_LIBRARY_PATH: /usr/sap/{{ hana_sid }}/HDB{{ hana_instance }}/exe
    PATH: /usr/sap/{{ hana_sid }}/HDB{{ hana_instance }}/exe:$PATH